import type {
  Category,
  Transaction,
  RecurringRule,
  Prediction,
  LocalStorageData,
} from "./types";

// Helper to generate consistent IDs
const generateId = (prefix: string, index: number): string =>
  `${prefix}-${index.toString().padStart(4, "0")}`;

// Helper to get date in the past
const daysAgo = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString();
};

// Helper to get future date
const daysAhead = (days: number): string => {
  const date = new Date();
  date.setDate(date.getDate() + days);
  return date.toISOString();
};

// Categories
export const mockCategories: Category[] = [
  {
    id: generateId("cat", 1),
    name: "Salary",
    color: "#22c55e",
    createdAt: daysAgo(180),
  },
  {
    id: generateId("cat", 2),
    name: "Groceries",
    color: "#3b82f6",
    createdAt: daysAgo(180),
  },
  {
    id: generateId("cat", 3),
    name: "Dining",
    color: "#f59e0b",
    createdAt: daysAgo(180),
  },
  {
    id: generateId("cat", 4),
    name: "Transportation",
    color: "#8b5cf6",
    createdAt: daysAgo(180),
  },
  {
    id: generateId("cat", 5),
    name: "Utilities",
    color: "#ef4444",
    createdAt: daysAgo(180),
  },
  {
    id: generateId("cat", 6),
    name: "Entertainment",
    color: "#ec4899",
    createdAt: daysAgo(180),
  },
  {
    id: generateId("cat", 7),
    name: "Shopping",
    color: "#06b6d4",
    createdAt: daysAgo(180),
  },
  {
    id: generateId("cat", 8),
    name: "Healthcare",
    color: "#14b8a6",
    createdAt: daysAgo(180),
  },
  {
    id: generateId("cat", 9),
    name: "Rent",
    color: "#ef4444",
    createdAt: daysAgo(180),
  },
  {
    id: generateId("cat", 10),
    name: "Subscriptions",
    color: "#f97316",
    createdAt: daysAgo(180),
  },
];

// Get category ID by name
const getCatId = (name: string): string => {
  const cat = mockCategories.find((c) => c.name === name);
  return cat?.id || mockCategories[0].id;
};

// Transactions - 6 months of history
export const mockTransactions: Transaction[] = [
  // Month 6 (180 days ago)
  {
    id: generateId("txn", 1),
    date: daysAgo(180),
    description: "Monthly Salary",
    amount: 5000,
    type: "credit",
    categoryId: getCatId("Salary"),
    createdAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
  {
    id: generateId("txn", 2),
    date: daysAgo(179),
    description: "Rent Payment",
    amount: -1500,
    type: "debit",
    categoryId: getCatId("Rent"),
    createdAt: daysAgo(179),
    updatedAt: daysAgo(179),
  },
  {
    id: generateId("txn", 3),
    date: daysAgo(178),
    description: "Electric Bill",
    amount: -120,
    type: "debit",
    categoryId: getCatId("Utilities"),
    createdAt: daysAgo(178),
    updatedAt: daysAgo(178),
  },
  {
    id: generateId("txn", 4),
    date: daysAgo(177),
    description: "Whole Foods",
    amount: -85.50,
    type: "debit",
    categoryId: getCatId("Groceries"),
    createdAt: daysAgo(177),
    updatedAt: daysAgo(177),
  },
  {
    id: generateId("txn", 5),
    date: daysAgo(175),
    description: "Netflix Subscription",
    amount: -15.99,
    type: "debit",
    categoryId: getCatId("Subscriptions"),
    createdAt: daysAgo(175),
    updatedAt: daysAgo(175),
  },
  {
    id: generateId("txn", 6),
    date: daysAgo(174),
    description: "Uber",
    amount: -32.50,
    type: "debit",
    categoryId: getCatId("Transportation"),
    createdAt: daysAgo(174),
    updatedAt: daysAgo(174),
  },
  {
    id: generateId("txn", 7),
    date: daysAgo(172),
    description: "Chipotle",
    amount: -14.75,
    type: "debit",
    categoryId: getCatId("Dining"),
    createdAt: daysAgo(172),
    updatedAt: daysAgo(172),
  },
  {
    id: generateId("txn", 8),
    date: daysAgo(170),
    description: "Target",
    amount: -67.30,
    type: "debit",
    categoryId: getCatId("Shopping"),
    createdAt: daysAgo(170),
    updatedAt: daysAgo(170),
  },

  // Month 5 (150 days ago)
  {
    id: generateId("txn", 9),
    date: daysAgo(150),
    description: "Monthly Salary",
    amount: 5000,
    type: "credit",
    categoryId: getCatId("Salary"),
    createdAt: daysAgo(150),
    updatedAt: daysAgo(150),
  },
  {
    id: generateId("txn", 10),
    date: daysAgo(149),
    description: "Rent Payment",
    amount: -1500,
    type: "debit",
    categoryId: getCatId("Rent"),
    createdAt: daysAgo(149),
    updatedAt: daysAgo(149),
  },
  {
    id: generateId("txn", 11),
    date: daysAgo(148),
    description: "Electric Bill",
    amount: -115,
    type: "debit",
    categoryId: getCatId("Utilities"),
    createdAt: daysAgo(148),
    updatedAt: daysAgo(148),
  },
  {
    id: generateId("txn", 12),
    date: daysAgo(147),
    description: "Trader Joe's",
    amount: -92.40,
    type: "debit",
    categoryId: getCatId("Groceries"),
    createdAt: daysAgo(147),
    updatedAt: daysAgo(147),
  },
  {
    id: generateId("txn", 13),
    date: daysAgo(145),
    description: "Spotify Premium",
    amount: -9.99,
    type: "debit",
    categoryId: getCatId("Subscriptions"),
    createdAt: daysAgo(145),
    updatedAt: daysAgo(145),
  },
  {
    id: generateId("txn", 14),
    date: daysAgo(144),
    description: "Gas Station",
    amount: -45.00,
    type: "debit",
    categoryId: getCatId("Transportation"),
    createdAt: daysAgo(144),
    updatedAt: daysAgo(144),
  },
  {
    id: generateId("txn", 15),
    date: daysAgo(142),
    description: "Movie Tickets",
    amount: -28.50,
    type: "debit",
    categoryId: getCatId("Entertainment"),
    createdAt: daysAgo(142),
    updatedAt: daysAgo(142),
  },
  {
    id: generateId("txn", 16),
    date: daysAgo(140),
    description: "Amazon Purchase",
    amount: -134.99,
    type: "debit",
    categoryId: getCatId("Shopping"),
    createdAt: daysAgo(140),
    updatedAt: daysAgo(140),
  },

  // Month 4 (120 days ago)
  {
    id: generateId("txn", 17),
    date: daysAgo(120),
    description: "Monthly Salary",
    amount: 5000,
    type: "credit",
    categoryId: getCatId("Salary"),
    createdAt: daysAgo(120),
    updatedAt: daysAgo(120),
  },
  {
    id: generateId("txn", 18),
    date: daysAgo(119),
    description: "Rent Payment",
    amount: -1500,
    type: "debit",
    categoryId: getCatId("Rent"),
    createdAt: daysAgo(119),
    updatedAt: daysAgo(119),
  },
  {
    id: generateId("txn", 19),
    date: daysAgo(118),
    description: "Water Bill",
    amount: -65,
    type: "debit",
    categoryId: getCatId("Utilities"),
    createdAt: daysAgo(118),
    updatedAt: daysAgo(118),
  },
  {
    id: generateId("txn", 20),
    date: daysAgo(117),
    description: "Whole Foods",
    amount: -105.20,
    type: "debit",
    categoryId: getCatId("Groceries"),
    createdAt: daysAgo(117),
    updatedAt: daysAgo(117),
  },
  {
    id: generateId("txn", 21),
    date: daysAgo(115),
    description: "Gym Membership",
    amount: -50,
    type: "debit",
    categoryId: getCatId("Healthcare"),
    createdAt: daysAgo(115),
    updatedAt: daysAgo(115),
  },
  {
    id: generateId("txn", 22),
    date: daysAgo(113),
    description: "Restaurant Dinner",
    amount: -78.90,
    type: "debit",
    categoryId: getCatId("Dining"),
    createdAt: daysAgo(113),
    updatedAt: daysAgo(113),
  },
  {
    id: generateId("txn", 23),
    date: daysAgo(110),
    description: "Uber Rides",
    amount: -41.25,
    type: "debit",
    categoryId: getCatId("Transportation"),
    createdAt: daysAgo(110),
    updatedAt: daysAgo(110),
  },

  // Month 3 (90 days ago)
  {
    id: generateId("txn", 24),
    date: daysAgo(90),
    description: "Monthly Salary",
    amount: 5000,
    type: "credit",
    categoryId: getCatId("Salary"),
    createdAt: daysAgo(90),
    updatedAt: daysAgo(90),
  },
  {
    id: generateId("txn", 25),
    date: daysAgo(89),
    description: "Rent Payment",
    amount: -1500,
    type: "debit",
    categoryId: getCatId("Rent"),
    createdAt: daysAgo(89),
    updatedAt: daysAgo(89),
  },
  {
    id: generateId("txn", 26),
    date: daysAgo(88),
    description: "Electric Bill",
    amount: -110,
    type: "debit",
    categoryId: getCatId("Utilities"),
    createdAt: daysAgo(88),
    updatedAt: daysAgo(88),
  },
  {
    id: generateId("txn", 27),
    date: daysAgo(87),
    description: "Safeway",
    amount: -88.75,
    type: "debit",
    categoryId: getCatId("Groceries"),
    createdAt: daysAgo(87),
    updatedAt: daysAgo(87),
  },
  {
    id: generateId("txn", 28),
    date: daysAgo(85),
    description: "Netflix Subscription",
    amount: -15.99,
    type: "debit",
    categoryId: getCatId("Subscriptions"),
    createdAt: daysAgo(85),
    updatedAt: daysAgo(85),
  },
  {
    id: generateId("txn", 29),
    date: daysAgo(84),
    description: "Coffee Shop",
    amount: -24.50,
    type: "debit",
    categoryId: getCatId("Dining"),
    createdAt: daysAgo(84),
    updatedAt: daysAgo(84),
  },
  {
    id: generateId("txn", 30),
    date: daysAgo(82),
    description: "Concert Tickets",
    amount: -120,
    type: "debit",
    categoryId: getCatId("Entertainment"),
    createdAt: daysAgo(82),
    updatedAt: daysAgo(82),
  },
  {
    id: generateId("txn", 31),
    date: daysAgo(80),
    description: "Best Buy",
    amount: -299.99,
    type: "debit",
    categoryId: getCatId("Shopping"),
    createdAt: daysAgo(80),
    updatedAt: daysAgo(80),
  },

  // Month 2 (60 days ago)
  {
    id: generateId("txn", 32),
    date: daysAgo(60),
    description: "Monthly Salary",
    amount: 5000,
    type: "credit",
    categoryId: getCatId("Salary"),
    createdAt: daysAgo(60),
    updatedAt: daysAgo(60),
  },
  {
    id: generateId("txn", 33),
    date: daysAgo(59),
    description: "Rent Payment",
    amount: -1500,
    type: "debit",
    categoryId: getCatId("Rent"),
    createdAt: daysAgo(59),
    updatedAt: daysAgo(59),
  },
  {
    id: generateId("txn", 34),
    date: daysAgo(58),
    description: "Gas Bill",
    amount: -75,
    type: "debit",
    categoryId: getCatId("Utilities"),
    createdAt: daysAgo(58),
    updatedAt: daysAgo(58),
  },
  {
    id: generateId("txn", 35),
    date: daysAgo(57),
    description: "Costco",
    amount: -145.30,
    type: "debit",
    categoryId: getCatId("Groceries"),
    createdAt: daysAgo(57),
    updatedAt: daysAgo(57),
  },
  {
    id: generateId("txn", 36),
    date: daysAgo(55),
    description: "Spotify Premium",
    amount: -9.99,
    type: "debit",
    categoryId: getCatId("Subscriptions"),
    createdAt: daysAgo(55),
    updatedAt: daysAgo(55),
  },
  {
    id: generateId("txn", 37),
    date: daysAgo(54),
    description: "Pharmacy",
    amount: -32.15,
    type: "debit",
    categoryId: getCatId("Healthcare"),
    createdAt: daysAgo(54),
    updatedAt: daysAgo(54),
  },
  {
    id: generateId("txn", 38),
    date: daysAgo(52),
    description: "Sushi Restaurant",
    amount: -65.40,
    type: "debit",
    categoryId: getCatId("Dining"),
    createdAt: daysAgo(52),
    updatedAt: daysAgo(52),
  },
  {
    id: generateId("txn", 39),
    date: daysAgo(50),
    description: "Gas Station",
    amount: -48.00,
    type: "debit",
    categoryId: getCatId("Transportation"),
    createdAt: daysAgo(50),
    updatedAt: daysAgo(50),
  },

  // Month 1 (30 days ago)
  {
    id: generateId("txn", 40),
    date: daysAgo(30),
    description: "Monthly Salary",
    amount: 5000,
    type: "credit",
    categoryId: getCatId("Salary"),
    createdAt: daysAgo(30),
    updatedAt: daysAgo(30),
  },
  {
    id: generateId("txn", 41),
    date: daysAgo(29),
    description: "Rent Payment",
    amount: -1500,
    type: "debit",
    categoryId: getCatId("Rent"),
    createdAt: daysAgo(29),
    updatedAt: daysAgo(29),
  },
  {
    id: generateId("txn", 42),
    date: daysAgo(28),
    description: "Electric Bill",
    amount: -125,
    type: "debit",
    categoryId: getCatId("Utilities"),
    createdAt: daysAgo(28),
    updatedAt: daysAgo(28),
  },
  {
    id: generateId("txn", 43),
    date: daysAgo(27),
    description: "Whole Foods",
    amount: -98.60,
    type: "debit",
    categoryId: getCatId("Groceries"),
    createdAt: daysAgo(27),
    updatedAt: daysAgo(27),
  },
  {
    id: generateId("txn", 44),
    date: daysAgo(25),
    description: "Gym Membership",
    amount: -50,
    type: "debit",
    categoryId: getCatId("Healthcare"),
    createdAt: daysAgo(25),
    updatedAt: daysAgo(25),
  },
  {
    id: generateId("txn", 45),
    date: daysAgo(23),
    description: "Pizza Delivery",
    amount: -35.80,
    type: "debit",
    categoryId: getCatId("Dining"),
    createdAt: daysAgo(23),
    updatedAt: daysAgo(23),
  },
  {
    id: generateId("txn", 46),
    date: daysAgo(21),
    description: "Uber Rides",
    amount: -38.90,
    type: "debit",
    categoryId: getCatId("Transportation"),
    createdAt: daysAgo(21),
    updatedAt: daysAgo(21),
  },
  {
    id: generateId("txn", 47),
    date: daysAgo(20),
    description: "Movies Streaming",
    amount: -12.99,
    type: "debit",
    categoryId: getCatId("Entertainment"),
    createdAt: daysAgo(20),
    updatedAt: daysAgo(20),
  },

  // Recent transactions (last 2 weeks)
  {
    id: generateId("txn", 48),
    date: daysAgo(14),
    description: "Trader Joe's",
    amount: -72.35,
    type: "debit",
    categoryId: getCatId("Groceries"),
    createdAt: daysAgo(14),
    updatedAt: daysAgo(14),
  },
  {
    id: generateId("txn", 49),
    date: daysAgo(12),
    description: "Coffee Shop",
    amount: -18.25,
    type: "debit",
    categoryId: getCatId("Dining"),
    createdAt: daysAgo(12),
    updatedAt: daysAgo(12),
  },
  {
    id: generateId("txn", 50),
    date: daysAgo(10),
    description: "Amazon Purchase",
    amount: -87.50,
    type: "debit",
    categoryId: getCatId("Shopping"),
    createdAt: daysAgo(10),
    updatedAt: daysAgo(10),
  },
  {
    id: generateId("txn", 51),
    date: daysAgo(7),
    description: "Gas Station",
    amount: -52.00,
    type: "debit",
    categoryId: getCatId("Transportation"),
    createdAt: daysAgo(7),
    updatedAt: daysAgo(7),
  },
  {
    id: generateId("txn", 52),
    date: daysAgo(5),
    description: "Restaurant Lunch",
    amount: -42.75,
    type: "debit",
    categoryId: getCatId("Dining"),
    createdAt: daysAgo(5),
    updatedAt: daysAgo(5),
  },
  {
    id: generateId("txn", 53),
    date: daysAgo(3),
    description: "Safeway",
    amount: -56.80,
    type: "debit",
    categoryId: getCatId("Groceries"),
    createdAt: daysAgo(3),
    updatedAt: daysAgo(3),
  },
  {
    id: generateId("txn", 54),
    date: daysAgo(1),
    description: "Netflix Subscription",
    amount: -15.99,
    type: "debit",
    categoryId: getCatId("Subscriptions"),
    createdAt: daysAgo(1),
    updatedAt: daysAgo(1),
  },
];

// Recurring Rules
export const mockRecurringRules: RecurringRule[] = [
  {
    id: generateId("rule", 1),
    description: "Monthly Salary",
    amount: 5000,
    type: "credit",
    categoryId: getCatId("Salary"),
    frequency: "monthly",
    startDate: daysAgo(180),
    endDate: null,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
  {
    id: generateId("rule", 2),
    description: "Rent Payment",
    amount: -1500,
    type: "debit",
    categoryId: getCatId("Rent"),
    frequency: "monthly",
    startDate: daysAgo(180),
    endDate: null,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
  {
    id: generateId("rule", 3),
    description: "Netflix Subscription",
    amount: -15.99,
    type: "debit",
    categoryId: getCatId("Subscriptions"),
    frequency: "monthly",
    startDate: daysAgo(180),
    endDate: null,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
  {
    id: generateId("rule", 4),
    description: "Spotify Premium",
    amount: -9.99,
    type: "debit",
    categoryId: getCatId("Subscriptions"),
    frequency: "monthly",
    startDate: daysAgo(180),
    endDate: null,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
  {
    id: generateId("rule", 5),
    description: "Gym Membership",
    amount: -50,
    type: "debit",
    categoryId: getCatId("Healthcare"),
    frequency: "monthly",
    startDate: daysAgo(180),
    endDate: null,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
  {
    id: generateId("rule", 6),
    description: "Electric Bill (est.)",
    amount: -120,
    type: "debit",
    categoryId: getCatId("Utilities"),
    frequency: "monthly",
    startDate: daysAgo(180),
    endDate: null,
    createdAt: daysAgo(180),
    updatedAt: daysAgo(180),
  },
];

// Manual Predictions
export const mockPredictions: Prediction[] = [
  {
    id: generateId("pred", 1),
    date: daysAhead(15),
    description: "Car Insurance Payment",
    amount: -450,
    type: "debit",
    categoryId: getCatId("Transportation"),
    isFromRecurring: false,
    recurringRuleId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId("pred", 2),
    date: daysAhead(25),
    description: "Vacation Flight",
    amount: -650,
    type: "debit",
    categoryId: getCatId("Entertainment"),
    isFromRecurring: false,
    recurringRuleId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: generateId("pred", 3),
    date: daysAhead(40),
    description: "Bonus Payment",
    amount: 2000,
    type: "credit",
    categoryId: getCatId("Salary"),
    isFromRecurring: false,
    recurringRuleId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

// Complete mock data
export const mockData: LocalStorageData = {
  transactions: mockTransactions,
  categories: mockCategories,
  recurringRules: mockRecurringRules,
  predictions: mockPredictions,
  settings: {
    theme: "dark",
    defaultTimePeriod: "1month",
  },
};

// Function to initialize mock data
export const initializeMockData = (): void => {
  if (typeof window === "undefined") return;

  const STORAGE_KEY = "onyx-cashflow-data";
  const existing = localStorage.getItem(STORAGE_KEY);

  if (!existing) {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(mockData));
    console.log("Mock data initialized");
  }
};
